app:
  main-exchange: main-exchange
  routing-key: q.queue-game
server:
  port: 8081
spring:
  rabbitmq:
    addresses: "localhost"
token:
  public: |
    AAAAB3NzaC1yc2EAAAADAQABAAACAQC65T8Ui5FE9rJ0JBluu/sqbMg3bAm17wpd7dyx6Lxt3DyMMXZJipFL62d0Ns3JGfWWmI+9sNmItJJGILeDgTsgA6oeDOIIy6GVmtQzFncXHfInK8kvIpGkDELzajtE5//qyAdAmpiyQkWhfSV+5tRn718/moICU/Tbpi7HggsFnsKgjcLH2aKK2R/a8aPWUC4fqoSy/Sm2w3ueYXyO7SZ9NdQ1MI3OesZqj37MG2gsJdz5SQwKEDKMkz9/3ikJ1Ces1RId9x/8C1FDQhcJ0c2A0gk30aHZDrxHxnANlOvmhDJosl9QaNoU97daONV4KvPAlO3d5/4t3684RBIdaFsLuuc/fqD/a4VjzS+q4dbP/hA+KfyvlGTN5M6uMIHqEY7PkpE5X0NU8w8zOvofllOjCqqOU24tluB1R8w6/McEV8mL79f6MIaSO/nanK+Hj0p/wLPGO5buYJeQdtsFLntIOIem8tZf0hYk9b1Hdd/9BQIRWdMHS5/HxiLrqeD75wzzVPKPw5OmUObEBhmS7L0J7rIbQz18qlqxLDKG5KQy+QmbRI1n8PJIr09/zs8k7SgBJrwdXA38o8jztW6YD+s6n9i7pPZwDhVI79GdDcxVbYRE3WG1JGIJh5TwEyuCiU/e69ISVCxMlIcT8prtISjJxVJRnQRQF/Zzhhm7msgbMw==
